site_name: Alana-Utils Documentation
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          handler: mkdocstrings.handlers.python
          options:
            show_source: true
            show_root_heading: true
            show_submodules: true
            docstring_style: google
          paths: [alana, '.']
nav:
  - Home: README.md
  - API Reference:
    - prompt: prompt.md
    - color: color.md
  - Testing: tests.md
  - Website Documentation: website.md